namespace InvoiceSoftware.Shared.Dtos.RecurringInvoices;

public record RecurringInvoiceDetailDto(
    Guid Id,
    Guid ClientId,
    string ClientName,
    string TemplateName,
    string? Notes,
    string? Terms,
    string? Footer,
    decimal TaxRate,
    string Currency,
    int FrequencyInterval,
    string Frequency,
    DateOnly StartDate,
    DateOnly? EndDate,
    int DueDays,
    bool IsActive,
    DateOnly? LastGeneratedDate,
    DateOnly NextInvoiceDate,
    int GeneratedCount,
    List<RecurringInvoiceLineItemDto> LineItems,
    decimal Subtotal,
    decimal TaxAmount,
    decimal Total,
    DateTime CreatedAt,
    DateTime? ModifiedAt);
