namespace InvoiceSoftware.Shared.Dtos.Expenses;

public record ExpenseDetailDto(
    Guid Id,
    string Category,
    string MerchantName,
    DateOnly ExpenseDate,
    string PaymentMethod,
    decimal Amount,
    string Currency,
    decimal TaxAmount,
    bool IsTaxInclusive,
    string? MerchantTaxNumber,
    string? GroupName,
    string? Notes,
    bool IsReimbursable,
    bool IsBillable,
    bool IsBilled,
    Guid? ClientId,
    string? ClientName,
    Guid? ProjectId,
    string? ProjectName,
    Guid? InvoiceId,
    string? InvoiceNumber,
    Guid? RecurringExpenseId,
    DateTime CreatedAt,
    DateTime? ModifiedAt);
