using InvoiceSoftware.Shared.Dtos.InvoiceTemplates;

namespace InvoiceSoftware.Shared.Dtos.Estimates;

public record EstimateDetailDto(
    Guid Id,
    string EstimateNumber,
    Guid ClientId,
    string ClientName,
    string? ClientCompanyName,
    string ClientEmail,
    string? ClientPhone,
    string? ClientStreet,
    string? ClientCity,
    string? ClientState,
    string? ClientPostalCode,
    string? ClientCountry,
    string Currency,
    DateOnly EstimateDate,
    DateOnly? ExpiryDate,
    int ValidDays,
    string Status,
    decimal TaxRate,
    string? Notes,
    string? Terms,
    Guid? PublicAccessToken,
    Guid? ConvertedInvoiceId,
    DateOnly? AcceptedDate,
    DateOnly? RejectedDate,
    List<EstimateLineItemDto> LineItems,
    decimal Subtotal,
    decimal TaxAmount,
    decimal Total,
    DateTime CreatedAt,
    DateTime? ModifiedAt,
    Guid? TemplateId = null,
    InvoiceTemplateDto? Template = null);
